# Site setings
name: "Ajay Banstola"
description: "A personal blog"
meta_description: "A personal blog about Javascript, Information technology and Front end development. Useful for programmers and software developers."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl:
production_url: https://ajay.banstola.com.np/
disqus: "Ajay Banstola"
mailchimp_url: "ajay.banstola@gmail.com"
cover_image: cover_1.jpg
lang: "en"

# Add your GA Tracking Id
ga_analytics: UA-144918260-1
url: "https://ajaybanstola.com.np"

# Author
author:
  name: "Ajay Banstola"
  image: "authorimage.jpg"
  greetings: "Hi there!"
  description: "My name is Ajay Banstola."
  bio: "I am an It student currently studying at Deerwalk Institute of Technology."
  twitter: "hyperLoafer"

# Twitter
twitter:
  username: "hyperlLoafer"
  card: "summary"

social:
  name: "Ajay Banstola"
  links:
    - "https://twitter.com/hyperLoafer"
    - "https://www.linkedin.com/in/ajay-banstola-aaa002128/"
    - "https://github.com/ajay-banstola"

# Social links
social_twitter: "ajay-banstola"
social_github: "ajay-banstola"
social_instagram: "a_jaaee"
social_linkedin: "ajay-banstola-aaa002128"
social_reddit: "reddit"

# Navigation
navigation:
  - text: Blog
    url: /
  - text: About
    url: /about
  - text: Glossary
    url: /glossary

# Required Plugins
plugins_dir:
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-compress-images
  - jekyll-crosspost-to-medium
  - jekyll-twitter-plugin

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: "posts"

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: "/page/:num/" # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ":title - page :num"

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: "date"

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  #  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: "posts"

  # Optional, the default tag to use, omit to disable
  tag: ""

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ""

  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: "index"

############################################################

############################################################
# Site configuration for the Auto-Pages feature
# The values here represent the defaults if nothing is set
autopages:
  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: true

  # Category pages, omit entire config element to disable
  categories:
    enabled: true
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts:
      - "autopage_category.html"
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: "Posts in category :cat"
    # Optional, the permalink for the  pagination page (:cat is replaced),
    # the pagination permalink path is then appended to this permalink structure
    permalink: "/category/:cat"

  # Collection pages, omit to disable
  collections:
    enabled: false
    layouts:
      - "autopage_collection.html"
    title: "Posts in collection :coll" # :coll is replaced by the collection name
    permalink: "/collection/:coll"

  # Tag pages, omit to disable
  tags:
    layouts:
      - "tag.html"
    title: "Posts tagged with :tag" # :tag is replaced by the tag name
    permalink: "/tag/:tag"

# Permalinks
permalink: /:title

# Markdown
markdown: kramdown

kramdown:
  footnote_backlink: "&#8617;&#65038;"

target-blank:
  add_css_classes: external-link
  noopener: false
  noreferrer: false

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - workflow
  - .idea
  - .git
  - Makefile
  - README.md

imageoptim:
  pngout: false
  svgo: true
  verbose: false

jekyll-minifier:
  preserve_php: true # Default: false
  remove_spaces_inside_tags: true # Default: true
  remove_multi_spaces: true # Default: true
  remove_comments: true # Default: true
  remove_intertag_spaces: true # Default: false
  remove_quotes: false # Default: false
  compress_css: true # Default: true
  compress_javascript: true # Default: true
  compress_json: true # Default: true
  simple_doctype: false # Default: false
  remove_script_attributes: false # Default: false
  remove_style_attributes: false # Default: false
  remove_link_attributes: false # Default: false
  remove_form_attributes: false # Default: false
  remove_input_attributes: false # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false # Default: false
  remove_https_protocol: false # Default: false
  preserve_line_breaks: false # Default: false
  simple_boolean_attributes: false # Default: false
  compress_js_templates: false # Default: false
  preserve_patterns: # Default: (empty)
  uglifier_args:
    harmony: true

jekyll-crosspost_to_medium:
  enabled: false
  cache: .jekyll-crosspost_to_medium
  status: draft
  license: all-rights-reserved
  text: "<p><i>Your (optional) signoff for the post.</i></p>"
  backdate: true

algolia:
  application_id: "X1A8Z9Y4AQ"
  index_name: "blog.polarize.ai"
  search_only_api_key: "842730120f989ff88dae38137ebd09be"
  files_to_exclude:
    - index.html
    - search.html
