---
- hosts: all

  connection: local

  tasks:
    - name: Add mappings to /etc/hosts
      tags:
        - hosts
      become: true
      blockinfile:
        path: /etc/hosts
        block: |
          {{ item.ip }} {{ item.name }}
        marker: "# {mark} polarize-ai/blog {{ item.name }}"
      with_items:
        - { name: blog.polarize.local, ip: 12.0.0.104 }

